In [7]:
import numpy as np
narrayA = np.array([[0,1],[2,3],[4,5]])
narrayB = np.array([[0,1,2,3],[4,5,6,7]])
result = np.dot(narrayA, narrayB)
print(result)
result.max()


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47